export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  name: 'name',
  value: 'value',
  placeholder: 'placeholder',
  placeholderStyle: 'placeholder-style',
  placeholderClass: 'placeholder-class',
  placeholderClassName: 'placeholder-class',
  disabled: 'disabled',
  maxlength: 'maxlength',
  autoFocus: 'auto-focus',
  focus: 'focus',
  fixed: 'fixed',
  autoHeight: 'auto-height',
  showCount: 'show-count',
  controlled: 'controlled',
  cursorSpacing: 'cursor-spacing',
  cursor: 'cursor',
  showConfirmBar: 'show-confirm-bar',
  selectionStart: 'selection-start',
  selectionEnd: 'selection-end',
  adjustPosition: 'adjust-position',
  holdKeyboard: 'hold-keyboard',
  onFocus: 'bindfocus',
  onBlur: 'bindblur',
  onLineChange: 'bindlinechange',
  onInput: 'bindinput',
  onConfirm: 'bindconfirm',
  onKeyboardHeightChange: 'bindkeyboardheightchange',
  confirmType: 'confirm-type',
  confirmHold: 'confirm-hold',
};

export const props = Object.values(alias);
