export declare const alias: {
  className: string;
  src: string;
  id: string;
  poster: string;
  objectFit: string;
  initialTime: string;
  duration: string;
  controls: string;
  autoplay: string;
  direction: string;
  loop: string;
  muted: string;
  showFullscreenBtn: string;
  showPlayBtn: string;
  showCenterPlayBtn: string;
  showMuteBtn: string;
  enableProgressGesture: string;
  mobilenetHintType: string;
  onPlay: string;
  onPause: string;
  onEnded: string;
  onTimeUpdate: string;
  onLoading: string;
  onError: string;
  onFullScreenChange: string;
  onTap: string;
  onClick: string;
  onUserAction: string;
};
export declare const props: string[];
