export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  src: 'src',
  mode: 'mode',
  autoplay: 'autoplay',
  muted: 'muted',
  orientation: 'orientation',
  objectFit: 'object-fit',
  background: 'background',
  minCache: 'min-cache',
  maxCache: 'max-cache',
  soundMode: 'sound-mode',
  autoPauseIfNavigate: 'auto-pause-if-navigate',
  autoPauseIfOpenNative: 'auto-pause-if-open-native',
  pictureInPictureMode: 'picture-in-picture-mode',
  onStateChange: 'bindstatechange',
  onFullscreenChange: 'bindfullscreenchange',
  onNetStatus: 'bindnetstatus',
  onAudioVolumeNotify: 'bindaudiovolumenotify',
  onEnterPictureInPicture: 'bindenterpictureinpicture',
  onLeavePictureInPicture: 'bindleavepictureinpicture',
  animation: 'animation',
};

export const props = Object.values(alias);
