export declare const alias: {
  id: string;
  className: string;
  style: string;
  value: string;
  name: string;
  type: string;
  password: string;
  placeholder: string;
  placeholderStyle: string;
  placeholderClass: string;
  placeholderClassName: string;
  disabled: string;
  maxlength: string;
  focus: string;
  confirmType: string;
  confirmHold: string;
  cursor: string;
  selectionStart: string;
  selectionEnd: string;
  randomNumber: string;
  controlled: string;
  onInput: string;
  onConfirm: string;
  onFocus: string;
  onBlur: string;
};
export declare const props: string[];
