export { useAppEvent, usePageEvent } from '@remax/framework-shared';
export { default as createAppConfig } from './createAppConfig';
export { default as createPageConfig } from './createPageConfig';
export { default as useQuery } from './hooks/useQuery';
export { default as useNativeEffect } from './hooks/useNativeEffect';
export { default as usePageInstance } from './hooks/usePageInstance';
export { default as bootstrap } from './bootstrap';
export { default as bootstrapMpa } from './bootstrapMpa';
export * from './api';
export * from './types';
