export const alias = {
  id: 'id',
  style: 'style',
  className: 'class',
  latitude: 'latitude',
  longitude: 'longitude',
  scale: 'scale',
  markers: 'markers',
  polyline: 'polyline',
  circles: 'circles',
  controls: 'controls',
  polygon: 'polygon',
  showLocation: 'show-location',
  includePoints: 'include-points',
  includePadding: 'include-padding',
  groundOverlays: 'ground-overlays',
  tileOverlay: 'tile-overlay',
  setting: 'setting',
  covers: 'covers',
  subkey: 'subkey',
  layerStyle: 'layer-style',
  rotate: 'rotate',
  skew: 'skew',
  enable3D: 'enable-3D',
  showCompass: 'show-compass',
  showScale: 'show-scale',
  enableOverlooking: 'enable-overlooking',
  enableZoom: 'enable-zoom',
  enableScroll: 'enable-scroll',
  enableRotate: 'enable-rotate',
  enableSatellite: 'enable-satellite',
  enableTraffic: 'enable-traffic',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onMarkerTap: 'bindmarkertap',
  onMarkerClick: 'bindmarkertap',
  onControlTap: 'bindcontroltap',
  onControlClick: 'bindcontroltap',
  onCalloutTap: 'bindcallouttap',
  onCalloutClick: 'bindcallouttap',
  onUpdated: 'bindupdated',
  onRegionChange: 'bindregionchange',
  onPoiTap: 'bindpoitap',
  onPoiClick: 'bindpoitap',
  animation: 'animation',
};

export const props = Object.values(alias);
