export const alias = {
  id: 'id',
  disableScroll: 'disable-scroll',
  hoverClass: 'hover-class',
  hoverClassName: 'hover-class',
  hoverStartTime: 'hover-start-time',
  hoverStayTime: 'hover-stay-time',
  hidden: 'hidden',
  className: 'class',
  style: 'style',
  animation: 'animation',
  hoverStopPropagation: 'hover-stop-propagation',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onTouchStart: 'bindtouchstart',
  onTouchMove: 'bindtouchmove',
  onTouchEnd: 'bindtouchend',
  onTouchCancel: 'bindtouchcancel',
  onLongTap: 'bindlongtap',
  onLongClick: 'bindlongtap',
  onTransitionEnd: 'bindtransitionend',
  onAnimationIteration: 'bindanimationiteration',
  onAnimationStart: 'bindanimationstart',
  onAnimationEnd: 'bindanimationend',
};

export const props = Object.values(alias);
