export const alias = {
  id: 'id',
  disableScroll: 'disable-scroll',
  hoverClass: 'hover-class',
  hoverClassName: 'hover-class',
  hoverStartTime: 'hover-start-time',
  hoverStayTime: 'hover-stay-time',
  hidden: 'hidden',
  className: 'class',
  style: 'style',
  animation: 'animation',
  hoverStopPropagation: 'hover-stop-propagation',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onTouchStart: 'bindtouchstart',
  onTouchMove: 'bindtouchmove',
  onTouchEnd: 'bindtouchend',
  onTouchCancel: 'bindtouchcancel',
  onLongTap: 'bindlongtap',
  onLongClick: 'bindlongtap',
  onLongPress: 'bindlongpress',
  onTransitionEnd: 'bindtransitionend',
  onAnimationIteration: 'bindanimationiteration',
  onAnimationStart: 'bindanimationstart',
  onAnimationEnd: 'bindanimationend',
  catchTouchMove: 'catchtouchmove',
  /** 无障碍属性 */
  ariaHidden: 'aria-hidden',
  ariaRole: 'aria-role',
  ariaLabel: 'aria-label',
  ariaChecked: 'aria-checked',
  ariaDisabled: 'aria-disabled',
  ariaDescribedby: 'aria-describedby',
  ariaExpanded: 'aria-expanded',
  ariaHaspopup: 'aria-haspopup',
  ariaSelected: 'aria-selected',
  ariaRequired: 'aria-required',
  ariaOrientation: 'aria-orientation',
  ariaValuemin: 'aria-valuemin',
  ariaValuemax: 'aria-valuemax',
  ariaValuenow: 'aria-valuenow',
  ariaReadonly: 'aria-readonly',
  ariaMultiselectable: 'aria-multiselectable',
  ariaControls: 'aria-controls',
  tabindex: 'tabindex',
  ariaLabelledby: 'aria-labelledby',
  ariaModal: 'aria-modal',
  ariaLive: 'aria-live',
  ariaAtomic: 'aria-atomic',
  ariaRelevant: 'aria-relevant',
};

export const props = Object.values(alias);
