export const alias = {
  id: 'id',
  autoFocus: 'auto-focus',
  className: 'class',
  focus: 'focus',
  alwayEmbed: 'always-embed',
  name: 'name',
  maxlength: 'maxlength',
  value: 'value',
  style: 'style',
  animation: 'animation',
  password: 'password',
  type: 'type',
  confirmType: 'confirm-type',
  confirmHold: 'confirm-hold',
  cursor: 'cursor',
  selectionStart: 'selection-start',
  selectionEnd: 'selection-end',
  adjustPosition: 'adjust-position',
  placeholder: 'placeholder',
  placeholderStyle: 'placeholder-style',
  placeholderClass: 'placeholder-class',
  placeholderClassName: 'placeholder-class',
  disabled: 'disabled',
  cursorSpacing: 'cursor-spacing',
  onInput: 'bindinput',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onFocus: 'bindfocus',
  onBlur: 'bindblur',
  onConfirm: 'bindconfirm',
  onKeyboardHeightChange: 'bindkeyboardheightchange',
};

export const props = Object.values(alias);
