export const alias = {
  className: 'class',
  id: 'id',
  style: 'style',
  type: 'type',
  plain: 'plain',
  disabled: 'disabled',
  loading: 'loading',
  formType: 'form-type',
  openType: 'open-type',
  hoverClass: 'hover-class',
  hoverClassName: 'hover-class',
  hoverStopPropagation: 'hover-stop-propagation',
  hoverStartTime: 'hover-start-time',
  hoverStayTime: 'hover-stay-time',
  lang: 'lang',
  sessionFrom: 'session-from',
  sendMessageTitle: 'send-message-title',
  sendMessagePath: 'send-message-path',
  sendMessageImg: 'send-message-img',
  size: 'size',
  appParameter: 'app-parameter',
  showMessageCard: 'show-message-card',
  onGetUserInfo: 'bindgetuserinfo',
  onContact: 'bindcontact',
  onGetPhoneNumber: 'bindgetphonenumber',
  onError: 'binderror',
  onOpenSetting: 'bindopensetting',
  onLaunchApp: 'bindlaunchapp',
  onTap: 'bindtap',
  onClick: 'bindtap',
  animation: 'animation',
};

export const props = Object.values(alias);
