export const alias = {
  className: 'class',
  id: 'id',
  style: 'style',
  animation: 'animation',
  type: 'type',
  plain: 'plain',
  disabled: 'disabled',
  loading: 'loading',
  formType: 'form-type',
  openType: 'open-type',
  hoverClass: 'hover-class',
  hoverClassName: 'hover-class',
  hoverStopPropagation: 'hover-stop-propagation',
  hoverStartTime: 'hover-start-time',
  hoverStayTime: 'hover-stay-time',
  lang: 'lang',
  sessionFrom: 'session-from',
  sendMessageTitle: 'send-message-title',
  sendMessagePath: 'send-message-path',
  sendMessageImg: 'send-message-img',
  size: 'size',
  appParameter: 'app-parameter',
  appPackageName: 'app-packagename',
  appBundleID: 'app-bundleid',
  appConnectID: 'app-connect-id',
  openId: 'open-id',
  groupId: 'group-id',
  publicId: 'public-id',
  shareType: 'share-type',
  shareMode: 'share-mode',
  shareMessageFriendInfo: 'share-message-friend-info',
  shareMessageTitle: 'share-message-title',
  shareMessageImg: 'share-message-img',
  showMessageCard: 'show-message-card',
  onGetUserInfo: 'bindgetuserinfo',
  onContact: 'bindcontact',
  onGetPhoneNumber: 'bindgetphonenumber',
  onError: 'binderror',
  onOpenSetting: 'bindopensetting',
  onLaunchApp: 'bindlaunchapp',
  onAddFriend: 'bindaddfriend',
  onAddGroupApp: 'bindaddgroupapp',
  onTap: 'bindtap',
  onClick: 'bindtap',
};

export const props = Object.values(alias);
