export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  src: 'src',
  title: 'title',
  initialTime: 'initial-time',
  controls: 'controls',
  autoPlay: 'autoplay',
  loop: 'loop',
  muted: 'muted',
  objectFit: 'objectFit',
  poster: 'poster',
  pageGesture: 'page-gesture',
  direction: 'direction',
  showProgress: 'show-progress',
  showFullscreenBtn: 'show-fullscreen-btn',
  enableProgressGesture: 'enable-progress-gesture',
  danmuList: 'danmu-list',
  danmuBtn: 'danmu-btn',
  enableDanmu: 'enable-danmu',
  showPlayBtn: 'show-play-btn',
  showCenterPlayBtn: 'show-center-play-btn',
  showMuteBtn: 'show-mute-btn',
  showNoWifiTip: 'show-no-wifi-tip',
  vslideGesture: 'vslide-gesture',
  vslideGestureInFullscreen: 'vslide-gesture-in-fullscreen',
  enablePlayGesture: 'enable-play-gesture',
  showRateBtn: 'show-rate-btn',
  showVslideBtnInFullscreen: 'show-vslide-btn-in-fullscreen',
  silentPlay: 'silent-play',
  onPlay: 'bindplay',
  onPause: 'bindpause',
  onEnded: 'bindended',
  onTimeupdate: 'bindtimeupdate',
  onFullscreenChange: 'bindfullscreenchange',
  onWaiting: 'bindwaiting',
  onError: 'binderror',
  onLoadedMetadata: 'bindloadedmetadata',
};

export const props = Object.values(alias);
