export declare const alias: {
  id: string;
  className: string;
  style: string;
  scrollX: string;
  scrollY: string;
  upperThreshold: string;
  lowerThreshold: string;
  scrollTop: string;
  scrollLeft: string;
  scrollIntoView: string;
  scrollWithAnimation: string;
  scrollAnimationDuration: string;
  enableBackToTop: string;
  trapScroll: string;
  onScrollToUpper: string;
  onScrollToLower: string;
  onScroll: string;
  onTouchStart: string;
  onTouchMove: string;
  onTouchEnd: string;
  onTouchCancel: string;
};
export declare const props: string[];
