export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  hidden: 'hidden',
  hoverClassName: 'hover-class',
  hoverStopPropagation: 'hover-stop-propagation',
  hoverStartTime: 'hover-start-time',
  hoverStayTime: 'hover-stay-time',
  onTap: 'bindtap',
  onLongTap: 'bindlongtap',
  onLongPress: 'bindlongpress',
  OnTouchStart: 'bindtouchstart',
  onTouchMove: 'bindtouchmove',
  onTouchCancel: 'bindtouchcancel',
  onTouchEnd: 'bindtouchend',
  onTouchForceChange: 'bindtouchforcechange',
  onTransitionEnd: 'bindtransitionend',
  onAnimationStart: 'bindanimationstart',
  onAnimationIteration: 'bindanimationiteration',
  onAnimationEnd: 'bindanimationend',
  catchTouchMove: 'catchtouchmove',
};

export const props = Object.values(alias);
