export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  scrollX: ' scroll-x',
  scrollY: ' scroll-y',
  upperThreshold: ' upper-threshold',
  lowerThreshold: ' lower-threshold',
  scrollTop: ' scroll-top',
  scrollLeft: ' scroll-left',
  scrollIntoView: ' scroll-into-view',
  scrollWithAnimation: ' scroll-with-animation',
  enableBackToTop: ' enable-back-to-top',
  onScrollToupper: ' bindscrolltoupper',
  onScrollTolower: ' bindscrolltolower',
  onScroll: ' bindscroll',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onTouchStart: 'bindtouchstart',
  onTouchMove: 'bindtouchmove',
  onTouchEnd: 'bindtouchend',
  onTouchCancel: 'bindtouchcancel',
  onLongTap: 'bindlongtap',
  onLongClick: 'bindlongtap',
};

export const props = Object.values(alias);
