export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  value: 'value',
  disabled: 'disabled',
  maxLength: 'maxlength',
  placeholder: 'placeholder',
  placeholderStyle: 'placeholder-style',
  placeholderClassName: 'placeholder-class',
  autoHeight: 'auto-height',
  cursor: 'cursor',
  autoFocus: 'auto-focus',
  confirmType: 'confirm-type',
  confirmHold: 'confirm-hold',
  focus: 'focus',
  fixed: 'fixed',
  cursorSpacing: 'cursor-spacing',
  showConfirmBar: 'show-confirm-bar',
  selectionStart: 'selection-start',
  selectionEnd: 'selection-end',
  adjustPosition: 'adjust-position',
  onFocus: 'bindfocus',
  onBlur: 'bindblur',
  onLinechange: 'bindlinechange',
  onInput: 'bindinput',
  onConfirm: 'bindconfirm',
};

export const props = Object.values(alias);
