export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  indicatorDots: 'indicator-dots',
  indicatorColor: 'indicator-color',
  indicatorActiveColor: 'indicator-active-color',
  autoplay: 'autoplay',
  current: 'current',
  interval: 'interval',
  duration: 'duration',
  circular: 'circular',
  vertical: 'vertical',
  previousMargin: 'previous-margin',
  nextMargin: 'next-margin',
  displayMultipleItems: 'display-multiple-items',
  skipHiddenItemLayout: 'skip-hidden-item-layout',
  easingFunction: 'easing-function',
  onChange: 'bindchange',
  onTransition: 'bindtransition',
  onAnimationFinish: 'bindanimationfinish',
  onTap: 'bindtap',
  onClick: 'bindtap',
  snapToEdge: 'snap-to-edge',
};

export const props = Object.values(alias);
