export declare const alias: {
  id: string;
  className: string;
  style: string;
  name: string;
  value: string;
  placeholder: string;
  placeholderStyle: string;
  placeholderClass: string;
  placeholderClassName: string;
  disabled: string;
  maxlength: string;
  focus: string;
  autoHeight: string;
  showCount: string;
  controlled: string;
  onInput: string;
  onFocus: string;
  onBlur: string;
  onConfirm: string;
};
export declare const props: string[];
