export const props = [
  'name',
  'value',
  'placeholder',
  'placeholder-style',
  'placeholder-class',
  'disabled',
  'maxlength',
  'focus',
  'auto-height',
  'show-count',
  'controlled',
  'onInput',
  'onFocus',
  'onBlur',
  'onConfirm',
];
