export declare const alias: {
  id: string;
  disableScroll: string;
  hoverClass: string;
  hoverClassName: string;
  hoverStartTime: string;
  hoverStayTime: string;
  hidden: string;
  className: string;
  style: string;
  animation: string;
  hoverStopPropagation: string;
  onClick: string;
  onTap: string;
  onTouchStart: string;
  onTouchMove: string;
  onTouchEnd: string;
  onTouchCancel: string;
  onLongTap: string;
  onLongClick: string;
  onTransitionEnd: string;
  onAnimationIteration: string;
  onAnimationStart: string;
  onAnimationEnd: string;
  onAppear: string;
  onDisappear: string;
  onFirstAppear: string;
};
export declare const props: string[];
