export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  url: 'url',
  mode: 'mode',
  autopush: 'autopush',
  muted: 'muted',
  enableCamera: 'enable-camera',
  autoFocus: 'auto-focus',
  orientation: 'orientation',
  beauty: 'beauty',
  beautyStyle: 'beauty-style',
  filter: 'filter',
  whiteness: 'whiteness',
  aspect: 'aspect',
  minBitrate: 'min-bitrate',
  maxBitrate: 'max-bitrate',
  audioQuality: 'audio-quality',
  waitingImage: 'waiting-image',
  waitingImageHash: 'waiting-image-hash',
  zoom: 'zoom',
  devicePosition: 'device-position',
  backgroundMute: 'background-mute',
  mirror: 'mirror',
  remoteMirror: 'remote-mirror',
  localMirror: 'local-mirror',
  audioReverbType: 'audio-reverb-type',
  enableMic: 'enable-mic',
  enableAgc: 'enable-agc',
  enableAns: 'enable-ans',
  audioVolumeType: 'audio-volume-type',
  videoWidth: 'video-width',
  videoHeight: 'video-height',
  onStateChange: 'bindstatechange',
  onNetStatus: 'bindnetstatus',
  onError: 'binderror',
  onBgmStart: 'bindbgmstart',
  onBgmProgress: 'bindbgmprogress',
  onBgmComplete: 'bindbgmcomplete',
};

export const props = Object.values(alias);
