export declare const alias: {
  id: string;
  style: string;
  className: string;
  latitude: string;
  longitude: string;
  scale: string;
  markers: string;
  polyline: string;
  circles: string;
  controls: string;
  polygon: string;
  showLocation: string;
  includePoints: string;
  includePadding: string;
  groundOverlays: string;
  tileOverlay: string;
  setting: string;
  onMarkerTap: string;
  onMarkerClick: string;
  onCalloutTap: string;
  onCalloutClick: string;
  onControlTap: string;
  onControlClick: string;
  onRegionChange: string;
  onTap: string;
  onClick: string;
};
export declare const props: string[];
