export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  longitude: 'longitude',
  latitude: 'latitude',
  scale: 'scale',
  markers: 'markers',
  polyline: 'polyline',
  polygons: 'polygons',
  circles: 'circles',
  controls: 'controls',
  includePoints: 'include-points',
  showLocation: 'show-location',
  enable3D: 'enable-3D',
  showCompass: 'show-compass',
  enableOverlooking: 'enable-overlooking',
  enableZoom: 'enable-zoom',
  enableScroll: 'enable-scroll',
  enableRotate: 'enable-rotate',
  onMarkerTap: 'bindmarkertap',
  onCalloutTap: 'bindcallouttap',
  onControlTap: 'bindcontroltap',
  onRegionChange: 'bindregionchange',
  onTap: 'bindtap',
  onUpdated: 'bindupdated',
  onPoitap: 'bindpoitap',
};

export const props = Object.values(alias);
