export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  scrollX: 'scroll-x',
  scrollY: 'scroll-y',
  upperThreshold: 'upper-threshold',
  lowerThreshold: 'lower-threshold',
  scrollTop: 'scroll-top',
  scrollLeft: 'scroll-left',
  scrollIntoView: 'scroll-into-view',
  scrollWithAnimation: 'scroll-with-animation',
  enableBackToTop: 'enable-back-to-top',
  enableFlex: 'enable-flex',
  onScrollToUpper: 'bindscrolltoupper',
  onScrollToLower: 'bindscrolltolower',
  onScroll: 'bindscroll',
  onTap: 'bindtap',
  onTouchStart: 'bindtouchstart',
  onTouchEnd: 'bindtouchend',
  onTouchMove: 'bindtouchmove',
  onTouchCancel: 'bindtouchcancel',
  onClick: 'bindtap',
  scrollAnchoring: 'scroll-anchoring',
  refresherEnabled: 'refresher-enabled',
  refresherThreshold: 'refresher-threshold',
  refresherDefaultStyle: 'refresher-default-style',
  refresherBackground: 'refresher-background',
  refresherTriggered: 'refresher-triggered',
  onRefresherPulling: 'bindrefresherpulling',
  onRefresherRefresh: 'bindrefresherrefresh',
  onRefresherRestore: 'bindrefresherrestore',
  onRefresherAbort: 'bindrefresherabort',
  enhanced: 'enhanced',
  bounces: 'bounces',
  showScrollbar: 'show-scrollbar',
  pagingEnabled: 'paging-enabled',
  fastDeceleration: 'fast-deceleration',
  onDragStart: 'binddragstart',
  onDragging: 'binddragging',
  onDragEnd: 'binddragend',
};

export const props = Object.values(alias);
