export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  src: 'src',
  duration: 'duration',
  controls: 'controls',
  danmuList: 'danmu-list',
  danmuBtn: 'danmu-btn',
  enableDanmu: 'enable-danmu',
  autoplay: 'autoplay',
  loop: 'loop',
  muted: 'muted',
  initialTime: 'initial-time',
  pageGesture: 'page-gesture',
  direction: 'direction',
  showProgress: 'show-progress',
  showFullscreenBtn: 'show-fullscreen-btn',
  showPlayBtn: 'show-play-btn',
  showCenterPlayBtn: 'show-center-play-btn',
  enableProgressGesture: 'enable-progress-gesture',
  objectFit: 'object-fit',
  poster: 'poster',
  showMuteBtn: 'show-mute-btn',
  title: 'title',
  playBtnPosition: 'play-btn-position',
  enablePlayGesture: 'enable-play-gesture',
  autoPauseIfNavigate: 'auto-pause-if-navigate',
  autoPauseIfOpenNative: 'auto-pause-if-open-native',
  vSlideGesture: 'vslide-gesture',
  vSlideGestureInfullscreen: 'vslide-gesture-in-fullscreen',
  onPlay: 'bindplay',
  onPause: 'bindpause',
  onEnded: 'bindended',
  onTimeUpdate: 'bindtimeupdate',
  onFullscreenChange: 'bindfullscreenchange',
  onWaiting: 'bindwaiting',
  onError: 'binderror',
  onProgress: 'bindprogress',
  animation: 'animation',
};

export const props = Object.values(alias);
